import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Code, Copy } from "lucide-react"
import { useState } from "react"

export function ViewCode({ code }: { code: string }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(code)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button 
          variant="outline" 
          size="icon"
          className="h-9 w-9"
          aria-label="View code"
        >
          <Code className="h-4 w-4" />
        </Button>
      </DialogTrigger>
      <DialogContent className="w-[800px] mx-auto overflow-auto h-[400px]">
        <DialogHeader>
          <DialogTitle>Generated Code</DialogTitle>
          <DialogDescription>
            AI-generated by Deepseek-v3
          </DialogDescription>
          <div>
            <Button
              size="sm"
              variant="outline"
              onClick={handleCopy}
              className="h-8 px-2 text-xs gap-1 mt-4"
            >
              <Copy className="h-3 w-3" />
              {copied ? "Copied!" : "Copy"}
            </Button>
            <pre className="p-4 mt-2 bg-gray-100 dark:bg-gray-800 rounded-md overflow-x-auto text-sm font-mono">
              {code}
            </pre>
          </div>
        </DialogHeader>
      
        <DialogFooter className="sm:justify-end mt-2">
          <DialogClose asChild>
            <Button type="button" variant="secondary">
              Close
            </Button>
          </DialogClose>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}